version: "3"
services:
  frontend:
    container_name: drupal9_jamesini_frontend
    build: .
    image: "uwbfritz/d9frontend:latest"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/var/www/html:rw
      - ./config/php.ini:/usr/local/etc/php/php.ini:ro
      - ./config/apache2.conf:/etc/apache2/apache2.conf:ro
      - ${HOME}/docker/d9privatefiles:/home/d9privatefiles:rw
      - ${HOME}/docker/d9tempfiles:/home/d9tempfiles:rw
      - ${HOME}/docker/d9publicfiles:/home/d9publicfiles:rw
    links:
      - db
  db:
    image: mysql:8.0
    volumes:
      - ./data:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: jamesini*
      MYSQL_DATABASE: drupal9_jamesini
      MYSQL_USER: drupal9_jamesini
      MYSQL_PASSWORD: drupal9_jamesini
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - db
